// <auto-generated />
namespace MauritiusGuideWS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MAULT147 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MAULT147));
        
        string IMigrationMetadata.Id
        {
            get { return "201803291020463_MAU-LT147"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
